-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 19:49:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaGestionUR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaGestionUR` DEFAULT CHARACTER SET utf8;
USE `SistemaGestionUR`;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NOT NULL,
  `nombreCompleto` VARCHAR(45) NULL,
  `tipoDocumento` ENUM('cedula', 'pasaporte', 'cedula de extranjeria') NULL,
  `numeroDocumento` VARCHAR(45) NULL UNIQUE,
  `correoElectronico` VARCHAR(50) NULL,
  `telefono` VARCHAR(20) NULL,
  `direccionInterna` VARCHAR(45) NULL,
  `rol` ENUM('propietario', 'inquilino') NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE (`usuario`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`idadmin`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solicitud` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('peticion', 'queja', 'reclamo', 'sugerencia') NOT NULL,
  `categoria` ENUM('servicios generales', 'seguridad', 'areas comunes') NULL,
  `descripcion` LONGTEXT NOT NULL,
  `estado` ENUM('radicada', 'en proceso', 'resuelta', 'cerrada') NOT NULL,
  `fechaHoraCreacion` DATETIME NOT NULL,
  `fechaActualizacion` DATETIME NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idsolicitud`),
  INDEX `fk_solicitud_usuario_idx` (`idusuario`),
  CONSTRAINT `fk_solicitud_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `reapertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reapertura` (
  `idreapertura` INT NOT NULL AUTO_INCREMENT,
  `justificacion` LONGTEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `idsolicitud` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idreapertura`),
  INDEX `fk_reapertura_solicitud_idx` (`idsolicitud`),
  INDEX `fk_reapertura_usuario_idx` (`idusuario`),
  CONSTRAINT `fk_reapertura_solicitud`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `solicitud` (`idsolicitud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reapertura_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `respuesta` (
  `idrespuesta` INT NOT NULL AUTO_INCREMENT,
  `oficioPDF` LONGBLOB NULL,
  `comentario` LONGTEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `idadmin` INT NOT NULL,
  `idreapertura` INT NULL,
  `idsolicitud` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`),
  INDEX `fk_respuesta_admin_idx` (`idadmin`),
  INDEX `fk_respuesta_solicitud_idx` (`idsolicitud`),
  INDEX `fk_respuesta_reapertura_idx` (`idreapertura`),
  CONSTRAINT `fk_respuesta_admin`
    FOREIGN KEY (`idadmin`)
    REFERENCES `admin` (`idadmin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_respuesta_solicitud`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `solicitud` (`idsolicitud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_respuesta_reapertura`
    FOREIGN KEY (`idreapertura`)
    REFERENCES `reapertura` (`idreapertura`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificacion` (
  `idcalificacion` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `idrespuesta` INT NOT NULL,
  PRIMARY KEY (`idcalificacion`),
  INDEX `fk_calificacion_respuesta_idx` (`idrespuesta`),
  CONSTRAINT `fk_calificacion_respuesta`
    FOREIGN KEY (`idrespuesta`)
    REFERENCES `respuesta` (`idrespuesta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidencia` (
  `idevidencia` INT NOT NULL AUTO_INCREMENT,
  `tipoArchivo` ENUM('pdf', 'video', 'imagen', 'audio', 'otro') NOT NULL,
  `archivo` LONGBLOB NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `fechaHoraCarga` DATETIME NULL,
  `idsolicitud` INT NOT NULL,
  PRIMARY KEY (`idevidencia`),
  INDEX `fk_evidencia_solicitud_idx` (`idsolicitud`),
  CONSTRAINT `fk_evidencia_solicitud`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `solicitud` (`idsolicitud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
