-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 19:49:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaGestionUR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaGestionUR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaGestionUR` DEFAULT CHARACTER SET = utf8 ;
USE `SistemaGestionUR` ;

-- -----------------------------------------------------
-- Table `SistemaGestionUR`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGestionUR`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NOT NULL,
  `nombreCompleto` VARCHAR(45) NULL,
  `tipoDocumento` ENUM('cedula', 'pasaporte', 'cedula de extranjeria') NULL,
  `numeroDocumento` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(50) NULL,
  `telefono` VARCHAR(20) NULL,
  `direccionInterna` VARCHAR(45) NULL,
  `rol` ENUM('propietario', 'inquilino') NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `numeroDocumento_UNIQUE` (`numeroDocumento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaGestionUR`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGestionUR`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaGestionUR`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGestionUR`.`solicitud` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('peticion', 'queja', 'reclamo', 'sugerencia') NOT NULL,
  `categoria` ENUM('servicios generales', 'seguridad', 'areas comunes') NULL,
  `descripcion` LONGTEXT NOT NULL,
  `estado` ENUM('radicada', 'en proceso', 'resuelta', 'cerrada') NOT NULL,
  `fechaHoraCreacion` DATETIME NOT NULL,
  `fechaActualizacion` DATETIME NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idsolicitud`),
  INDEX `fk_Solicitud_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitud_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `SistemaGestionUR`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaGestionUR`.`reapertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGestionUR`.`reapertura` (
  `idreapertura` INT NOT NULL AUTO_INCREMENT,
  `justificacion` LONGTEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `idsolicitud` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idreapertura`),
  INDEX `fk_reapertura_Solicitud1_idx` (`idsolicitud` ASC) VISIBLE,
  INDEX `fk_reapertura_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_reapertura_Solicitud1`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `SistemaGestionUR`.`solicitud` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reapertura_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `SistemaGestionUR`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaGestionUR`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGestionUR`.`respuesta` (
  `idrespuesta` INT NOT NULL AUTO_INCREMENT,
  `oficioPDF` VARBINARY(8000) NULL,
  `comentario` LONGTEXT BINARY NOT NULL,
  `fecha` DATE NOT NULL,
  `idadmin` INT NOT NULL,
  `idreapertura` INT NOT NULL,
  `idsolicitud` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`),
  INDEX `fk_respuesta_admin1_idx` (`idadmin` ASC) VISIBLE,
  INDEX `fk_respuesta_reapertura1_idx` (`idreapertura` ASC, `idsolicitud` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_admin1`
    FOREIGN KEY (`idadmin`)
    REFERENCES `SistemaGestionUR`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_reapertura1`
    FOREIGN KEY (`idreapertura` , `idsolicitud`)
    REFERENCES `SistemaGestionUR`.`reapertura` (`idreapertura` , `idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SistemaGestionUR`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGestionUR`.`calificacion` (
  `idcalificacion` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `idrespuesta` INT NOT NULL,
  PRIMARY KEY (`idcalificacion`),
  INDEX `fk_claifica_respuesta1_idx` (`idrespuesta` ASC) VISIBLE,
  CONSTRAINT `fk_claifica_respuesta1`
    FOREIGN KEY (`idrespuesta`)
    REFERENCES `SistemaGestionUR`.`respuesta` (`idrespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaGestionUR`.`evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaGestionUR`.`evidencia` (
  `idevidencia` INT NOT NULL AUTO_INCREMENT,
  `tipoArchivo` ENUM('pdf', 'video', 'imagen', 'audio', 'otro') NOT NULL,
  `archivo` VARBINARY(8000) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `fechaHoraCarga` DATETIME NULL,
  `idsolicitud` INT NOT NULL,
  PRIMARY KEY (`idevidencia`),
  INDEX `fk_evidencia_Solicitud_idx` (`idsolicitud` ASC) VISIBLE,
  CONSTRAINT `fk_evidencia_Solicitud`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `SistemaGestionUR`.`solicitud` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
